import PyPDF2
import os

# PDF文件映射 - 根据文件名识别报告
pdf_mapping = {
    'ai-fact-check-2026': {
        'file': '小艺深度研究报告-AI时代的信息质量保障：2026年系统性事实核查与风险管理体系研究@xiaoyi.huawei.com_20260331082108.pdf',
        'title': 'AI时代的信息质量保障',
        'skip_header': '小艺深度研究'
    },
    'prompt-engineering-guide': {
        'file': 'Prompt Engineering_v7.pdf',
        'title': '提示工程完全指南',
        'skip_header': None
    }
}

# 其他kimi artifact文件需要识别
kimi_files = [
    'kimi_artifact_1775001069220.pdf',
    'kimi_artifact_1775001027284.pdf',
    'kimi_artifact_1775000977359.pdf',
    'kimi_artifact_1775000838752.pdf'
]

def extract_pdf_content(pdf_path, max_chars=18000):
    """提取PDF内容"""
    try:
        with open(pdf_path, 'rb') as file:
            pdf_reader = PyPDF2.PdfReader(file)
            num_pages = len(pdf_reader.pages)
            
            full_text = ""
            for page_num in range(min(num_pages, 10)):  # 最多读取10页
                try:
                    page = pdf_reader.pages[page_num]
                    text = page.extract_text()
                    if text:
                        full_text += text + "\n"
                    if len(full_text) > max_chars:
                        break
                except:
                    continue
            
            return full_text[:max_chars], num_pages
    except Exception as e:
        return f"Error: {str(e)}", 0

def text_to_html(text, skip_header=None):
    """将文本转换为HTML格式"""
    lines = text.split('\n')
    html_lines = []
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
        # 跳过页眉页脚
        if skip_header and skip_header in line and len(line) < 30:
            continue
        if line.isdigit() and len(line) < 3:
            continue
        # 处理标题
        if line.startswith('第') and '章' in line[:10]:
            html_lines.append(f'<h2>{line}</h2>')
        elif len(line) > 3 and line[0].isdigit() and '.' in line[:5]:
            html_lines.append(f'<h3>{line}</h3>')
        elif '.....' in line or '....' in line:
            continue
        elif '目录' in line and len(line) < 10:
            continue
        elif '摘要' in line and len(line) < 10:
            html_lines.append(f'<h2>{line}</h2>')
        elif len(line) > 5:
            # 清理特殊字符
            clean_line = line.replace('\uf0b7', '-').replace('\uf0a7', '-').replace('\u2022', '-')
            html_lines.append(f'<p>{clean_line}</p>')
    
    return '\n'.join(html_lines)

pdf_dir = "c:/Users/ryuub/WorkBuddy/Claw/obtstar.top"

# 构建输出
output_lines = []
output_lines.append("const REPORT_CONTENTS = {")

# 处理已知的PDF文件
for report_id, info in pdf_mapping.items():
    pdf_path = os.path.join(pdf_dir, info['file'])
    if os.path.exists(pdf_path):
        output_lines.append(f'  "{report_id}": {{')
        output_lines.append(f'    id: "{report_id}",')
        output_lines.append(f'    title: "{info["title"]}",')
        
        content, total_pages = extract_pdf_content(pdf_path)
        output_lines.append(f'    totalPages: {total_pages},')
        output_lines.append(f'    sections: [')
        output_lines.append(f'      {{')
        output_lines.append(f'        title: "完整内容",')
        output_lines.append(f'        level: 1,')
        
        html_content = text_to_html(content, info.get('skip_header'))
        html_content = html_content.replace('`', '\\`')
        output_lines.append(f'        content: `{html_content}`')
        output_lines.append(f'      }}')
        output_lines.append(f'    ]')
        output_lines.append(f'  }},')

# 处理kimi artifact文件 - 需要识别是哪个报告
kimi_report_mapping = {
    'digital-transform-2024-2030': 'kimi_artifact_1775000838752.pdf',
    'knowledge-memory-arch': 'kimi_artifact_1775000977359.pdf',
    'data-stream-micro-light': 'kimi_artifact_1775001027284.pdf',
    'ai-coding-tools-growth': 'kimi_artifact_1775001069220.pdf',
}

report_titles = {
    'digital-transform-2024-2030': '个人与小微企业数字化转型',
    'knowledge-memory-arch': '超大规模知识记忆存储架构',
    'data-stream-micro-light': '数据洪流与微光',
    'ai-coding-tools-growth': 'AI编程工具成长路径',
}

for report_id, pdf_file in kimi_report_mapping.items():
    pdf_path = os.path.join(pdf_dir, pdf_file)
    if os.path.exists(pdf_path):
        output_lines.append(f'  "{report_id}": {{')
        output_lines.append(f'    id: "{report_id}",')
        output_lines.append(f'    title: "{report_titles[report_id]}",')
        
        content, total_pages = extract_pdf_content(pdf_path)
        output_lines.append(f'    totalPages: {total_pages},')
        output_lines.append(f'    sections: [')
        output_lines.append(f'      {{')
        output_lines.append(f'        title: "完整内容",')
        output_lines.append(f'        level: 1,')
        
        html_content = text_to_html(content, 'Generated by Kimi AI')
        html_content = html_content.replace('`', '\\`')
        output_lines.append(f'        content: `{html_content}`')
        output_lines.append(f'      }}')
        output_lines.append(f'    ]')
        output_lines.append(f'  }},')

output_lines.append("};")
output_lines.append("")
output_lines.append("// 导出数据供页面使用")
output_lines.append("if (typeof module !== 'undefined' && module.exports) {")
output_lines.append("  module.exports = { REPORT_CONTENTS };")
output_lines.append("}")

# 写入文件（输出到 <repo>/docs/data/）
output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'docs', 'data', 'report-contents.js')
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(output_lines))

print("report-contents.js 已更新，包含所有PDF内容")
