#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
将 _all_pdfs_content.txt 中的 PDF 内容转换为网站 chunk.js 和 manifest.json 文件
"""

import re
import json
import os
import html
import sys
import io

# 强制 stdout/stderr 用 UTF-8
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

# ─────────────────────────────────────────────
# 配置：PDF 文件名 → 报告 ID 的映射
# ─────────────────────────────────────────────
PDF_TO_REPORT = {
    'Prompt Engineering_v7.pdf': 'prompt-engineering-v7',
    'kimi_artifact_1775000838752.pdf': 'digital-transform-2024-2030',
    'kimi_artifact_1775000977359.pdf': 'knowledge-memory-arch',
    'kimi_artifact_1775001027284.pdf': 'data-stream-micro-light',
    'kimi_artifact_1775001069220.pdf': 'ai-coding-tools-growth',
}
# 小艺报告需要特殊处理（文件名很长）
XIAOYI_REPORT_ID = 'ai-fact-check-2026'

# 每个 chunk 包含的最大页数
PAGES_PER_CHUNK = 15

# 输出目录（相对于本脚本位置：<repo>/docs/data/reports-content）
OUTPUT_BASE = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'docs', 'data', 'reports-content')

# ─────────────────────────────────────────────
# 辅助函数
# ─────────────────────────────────────────────

def escape_backtick(text):
    """转义 JS 模板字符串中的反引号和 ${ """
    text = text.replace('\\', '\\\\')
    text = text.replace('`', '\\`')
    text = text.replace('${', '\\${')
    return text

def clean_page_text(raw_text):
    """清理页面文本：去掉多余空行，整理格式"""
    lines = raw_text.split('\n')
    cleaned = []
    for line in lines:
        line = line.strip()
        if line:
            cleaned.append(line)
    return '\n'.join(cleaned)

def text_to_html(text):
    """将纯文本转换为 HTML 格式"""
    lines = text.split('\n')
    html_parts = []
    in_list = False
    
    for line in lines:
        line = line.strip()
        if not line:
            if in_list:
                html_parts.append('</ul>')
                in_list = False
            continue
        
        # 检测标题层级（数字开头的章节）
        if re.match(r'^\d+\.\d+\s+', line) or re.match(r'^[一二三四五六七八九十]+[、．.]\s*', line):
            if in_list:
                html_parts.append('</ul>')
                in_list = False
            escaped = html.escape(line)
            html_parts.append(f'<h3>{escaped}</h3>')
        elif re.match(r'^\d+\.\s+\S', line) and len(line) < 60:
            if in_list:
                html_parts.append('</ul>')
                in_list = False
            escaped = html.escape(line)
            html_parts.append(f'<h3>{escaped}</h3>')
        # 检测表格标题行
        elif re.match(r'^表格$|^图表$|^表\d+|^图\d+', line):
            if in_list:
                html_parts.append('</ul>')
                in_list = False
            escaped = html.escape(line)
            html_parts.append(f'<p><strong>{escaped}</strong></p>')
        # 检测列表项（• · - * 开头）
        elif re.match(r'^[•·\-\*]\s+', line) or re.match(r'^\d+[.）)]\s+.{5,}', line):
            if not in_list:
                html_parts.append('<ul>')
                in_list = True
            content = re.sub(r'^[•·\-\*\d）)\.]\s+', '', line)
            escaped = html.escape(content)
            html_parts.append(f'<li>{escaped}</li>')
        else:
            if in_list:
                html_parts.append('</ul>')
                in_list = False
            escaped = html.escape(line)
            html_parts.append(f'<p>{escaped}</p>')
    
    if in_list:
        html_parts.append('</ul>')
    
    return '\n'.join(html_parts)

def extract_section_title(page_text, page_num):
    """从页面文本提取章节标题（取最能代表内容的行）"""
    lines = [l.strip() for l in page_text.split('\n') if l.strip()]
    if not lines:
        return f'第 {page_num} 页'
    
    # 常见的页眉/页脚噪音词，遇到这些跳过
    NOISE_PATTERNS = [
        r'^Prompt Engineering\s+Prompt Engineering$',
        r'^小艺深度研究$',
        r'^内容由\s*AI\s*生成',
        r'^\d+$',  # 纯数字页码
        r'^Generated by',
        r'^www\.',
        r'^http',
        r'^February \d+',
        r'^©',
        r'^kimi',
    ]
    
    def is_noise(line):
        for pattern in NOISE_PATTERNS:
            if re.match(pattern, line, re.IGNORECASE):
                return True
        return False
    
    # 优先找章节标题行（有中文章节编号）
    for line in lines:
        if is_noise(line):
            continue
        # 中文章节号模式
        if re.match(r'^[一二三四五六七八九十百]+[章节、，。]', line) or \
           re.match(r'^\d+\.\s+[\u4e00-\u9fff]', line) or \
           re.match(r'^第[一二三四五六七八九十百\d]+[章节部]', line):
            if len(line) <= 60:
                return line
    
    # 找第一个非噪音、有意义的行
    for line in lines[:10]:
        if is_noise(line):
            continue
        # 跳过太短（< 4字符）和太长（> 60字符）的行
        if len(line) < 4 or len(line) > 60:
            continue
        # 跳过全是英文且重复的行（如 "Prompt Engineering Prompt Engineering"）
        words = line.split()
        if len(words) >= 2 and len(words) % 2 == 0:
            half = words[:len(words)//2]
            if half == words[len(words)//2:]:
                continue  # 重复行
        # 去掉行号或特殊字符开头
        clean = re.sub(r'^[\d\s\-=\.]+', '', line).strip()
        if clean and len(clean) >= 3:
            return clean[:50]
    
    # 最后备用：返回第一行截断
    for line in lines:
        if not is_noise(line) and len(line) > 2:
            return line[:40]
    
    return f'第 {page_num} 页'

def pages_to_sections(pages):
    """将页面列表转换为 sections 数组，每个页面为一个 section"""
    sections = []
    for i, (page_num, page_text) in enumerate(pages):
        cleaned = clean_page_text(page_text)
        if not cleaned:
            continue
        
        title = extract_section_title(cleaned, page_num)
        html_content = text_to_html(cleaned)
        
        sections.append({
            'title': title,
            'level': 1,
            'content_raw': html_content,
            'page_num': page_num
        })
    
    return sections

def group_pages_into_sections(pages, target_sections_per_chunk=5):
    """将多个页面分组成 sections（每3页一个section）"""
    sections = []
    group_size = 3  # 每3页合并为一个section
    
    for i in range(0, len(pages), group_size):
        group = pages[i:i+group_size]
        if not group:
            continue
        
        first_page_num = group[0][0]
        last_page_num = group[-1][0]
        
        # 合并文本
        combined_text = '\n\n'.join([clean_page_text(text) for _, text in group if clean_page_text(text)])
        if not combined_text:
            continue
        
        # 取第一页的标题
        title = extract_section_title(group[0][1], first_page_num)
        page_range_str = f'第 {first_page_num}-{last_page_num} 页' if first_page_num != last_page_num else f'第 {first_page_num} 页'
        
        html_content = text_to_html(combined_text)
        
        sections.append({
            'title': title,
            'level': 1,
            'content_raw': html_content,
            'page_num': first_page_num,
            'page_range': f'{first_page_num}-{last_page_num}'
        })
    
    return sections

def generate_chunk_js(report_id, chunk_index, page_range_str, sections):
    """生成 chunk.js 文件内容"""
    report_id_js = report_id.replace('-', '_')
    
    sections_js = []
    for sec in sections:
        title_escaped = sec['title'].replace('\\', '\\\\').replace("'", "\\'")
        content_escaped = escape_backtick(sec['content_raw'])
        
        sec_js = f"""    {{
      title: '{title_escaped}',
      level: {sec['level']},
      content: `{content_escaped}`
    }}"""
        sections_js.append(sec_js)
    
    sections_str = ',\n'.join(sections_js)
    
    return f"""// 报告: {report_id} - 第{chunk_index}块
// 页数: {page_range_str}

window.REPORT_CHUNK_{report_id_js}_{chunk_index} = {{
  reportId: "{report_id}",
  chunkIndex: {chunk_index},
  pageRange: "{page_range_str}",
  sections: [
{sections_str}
  ]
}};
"""

def generate_manifest(report_id, total_pages, chunks_info):
    """生成 manifest.json 文件内容"""
    chunks = []
    for ci in chunks_info:
        chunks.append({
            "index": ci['index'],
            "file": f"chunk-{ci['index']}.js",
            "sections": ci['section_titles'],
            "pageRange": ci['page_range'],
            "size": ci['size']
        })
    
    manifest = {
        "id": report_id,
        "title": "",  # Will be filled in
        "totalPages": total_pages,
        "totalChunks": len(chunks),
        "chunks": chunks
    }
    return manifest

# ─────────────────────────────────────────────
# 报告元数据
# ─────────────────────────────────────────────
REPORT_TITLES = {
    'prompt-engineering-v7': 'Prompt Engineering 提示工程',
    'digital-transform-2024-2030': '个人与小微企业数字化转型',
    'knowledge-memory-arch': '超大规模知识记忆存储架构',
    'data-stream-micro-light': '数据洪流与微光',
    'ai-coding-tools-growth': 'AI编程工具销量增长策略',
    'ai-fact-check-2026': 'AI时代的信息质量保障',
}

# ─────────────────────────────────────────────
# 主处理逻辑
# ─────────────────────────────────────────────

def parse_pdf_content(content_text):
    """解析 PDF 内容文本，返回 {filename: [(page_num, page_text), ...]}"""
    result = {}
    
    # 按文件分割
    parts = re.split(r'={80}\nFILE: (.+?)\n={80}', content_text)
    
    for i in range(1, len(parts), 2):
        filename = parts[i].strip()
        file_content = parts[i+1] if i+1 < len(parts) else ''
        
        # 按页分割
        page_splits = re.split(r'\n--- Page (\d+) ---\n', file_content)
        # page_splits[0] is header ([Total pages: N])
        
        pages = []
        for j in range(1, len(page_splits), 2):
            page_num = int(page_splits[j])
            page_text = page_splits[j+1] if j+1 < len(page_splits) else ''
            pages.append((page_num, page_text))
        
        result[filename] = pages
    
    return result

def process_report(report_id, pages, output_dir):
    """处理单个报告，生成所有 chunk.js 和 manifest.json"""
    os.makedirs(output_dir, exist_ok=True)
    
    total_pages = len(pages)
    
    # 分 chunk（每 PAGES_PER_CHUNK 页一个 chunk）
    chunk_infos = []
    
    for chunk_idx, start in enumerate(range(0, total_pages, PAGES_PER_CHUNK)):
        chunk_pages = pages[start:start + PAGES_PER_CHUNK]
        
        first_page = chunk_pages[0][0]
        last_page = chunk_pages[-1][0]
        page_range_str = f'{first_page}-{last_page}'
        
        # 将页面分组为 sections（每3页一组）
        sections = group_pages_into_sections(chunk_pages)
        
        if not sections:
            continue
        
        # 生成 chunk.js
        chunk_js = generate_chunk_js(report_id, chunk_idx, page_range_str, sections)
        chunk_file = os.path.join(output_dir, f'chunk-{chunk_idx}.js')
        with open(chunk_file, 'w', encoding='utf-8') as f:
            f.write(chunk_js)
        
        file_size = os.path.getsize(chunk_file)
        size_str = f'约{file_size // 1024}KB'
        
        section_titles = [s['title'] for s in sections]
        chunk_infos.append({
            'index': chunk_idx,
            'page_range': page_range_str,
            'section_titles': section_titles,
            'size': size_str
        })
        
        print(f'  ✅ chunk-{chunk_idx}.js: 页{page_range_str}, {len(sections)}个section, {size_str}')
    
    # 生成 manifest.json
    manifest = generate_manifest(report_id, total_pages, chunk_infos)
    manifest['title'] = REPORT_TITLES.get(report_id, report_id)
    
    manifest_file = os.path.join(output_dir, 'manifest.json')
    with open(manifest_file, 'w', encoding='utf-8') as f:
        json.dump(manifest, f, ensure_ascii=False, indent=2)
    
    print(f'  ✅ manifest.json: {total_pages}页, {len(chunk_infos)}个chunk')
    return chunk_infos

# ─────────────────────────────────────────────
# 入口
# ─────────────────────────────────────────────

if __name__ == '__main__':
    print('📂 读取 PDF 内容...')
    with open('C:/Users/ryuub/WorkBuddy/Claw/obtstar.com/_all_pdfs_content.txt', 'r', encoding='utf-8') as f:
        all_content = f.read()
    
    print('🔍 解析各 PDF 内容...')
    pdf_pages = parse_pdf_content(all_content)
    
    print(f'📄 找到 {len(pdf_pages)} 个 PDF:')
    for fname, pages in pdf_pages.items():
        print(f'  - {fname}: {len(pages)} 页')
    
    print()
    
    # 处理每个报告
    for pdf_name, pages in pdf_pages.items():
        # 确定 report_id
        if pdf_name in PDF_TO_REPORT:
            report_id = PDF_TO_REPORT[pdf_name]
        elif '小艺' in pdf_name or 'xiaoyi' in pdf_name.lower():
            report_id = XIAOYI_REPORT_ID
        else:
            print(f'⚠️  未知 PDF: {pdf_name}, 跳过')
            continue
        
        output_dir = os.path.join(OUTPUT_BASE, report_id)
        print(f'\n🚀 处理 {report_id} ({len(pages)} 页)...')
        process_report(report_id, pages, output_dir)
    
    print('\n✅ 所有报告处理完成！')
